djangoBoard/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('signup/', views.SingUp.as_view(), name='signup'),
    path('mypage/', views.userinfo, name='mypage'),
]

djangoBoard/board/urls.py
from django.urls import path
from board import views
from board.views import BoardListView, BoardDetailView

app_name = 'board'
urlpatterns = [
    path('', views.BoardListView.as_view(), name = 'boardList'),
    path('<int:pk>/', views.BoardDetailView.as_view(), name = 'boardDetail'),
    path('write/', views.BoardWriteView, name = 'boardWrite'),
    path('write/<int:pk>/', views.BoardEditView, name = 'boardEdit'),
    path('delete/<int:pk>/', views.BoardDeleteView, name = 'boardDelete'),
]

djangoBoard/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('admin/', admin.site.urls),
    path('board/', include('board.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

djangoBoard/accounts/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Profile(models.Model):
    class Meta:
        verbose_name = 'Profile'
        verbose_name_plural = 'Profile'

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    nick = models.CharField(verbose_name = 'NickName', max_length=50, blank=True, unique=True)
    birth_date = models.DateTimeField(null=True, blank=True, help_text='ex) YYYY-MM-DD')
    aboutMe = models.TextField(blank=True, help_text='Introduce yourself', max_length=1000)

djangoBoard/board/models.py
from django.db import models

# Create your models here.
class Board(models.Model):
    writer = models.CharField(max_length=50, default='')
    title = models.CharField(max_length=100, null=False)
    contents = models.TextField(blank=True)
    createTime = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-createTime']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('board-detail', args=[str(self.id)])

djangoBoard/accounts/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse
from django.views import generic
from accounts.form import UserCreationMultiForm
from django.contrib.auth.decorators import login_required
from accounts.models import Profile
from django.http import Http404
# Create your views here.
class SingUp(generic.CreateView):
    form_class = UserCreationMultiForm
    success_url = reverse_lazy('login')
    template_name = 'signup.html'

    def form_valid(self, form):
        user = form['user'].save()
        profile = form['profile'].save(commit=False)
        profile.user = user
        profile.save()
        return redirect(reverse('login'))

@login_required
def userinfo(request):
    reqUser = request.user
    try:
        reqProfile = Profile.objects.get(user=reqUser)
        context = {
            'id' : reqUser.username,
            'nick' : reqProfile.nick,
            'birth_date' : reqProfile.birth_date,
            'aboutMe' : reqProfile.aboutMe,
            }
    except Profile.DoesNotExist:
        raise Http404("프로필 정보를 확인할 수 없는 관리자 계정 Can't verify profile information for manager account")

    return render(request, 'mypage.html', context=context)

djangoBoard/board/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views import generic
from django.views.generic import ListView, DetailView
from board.models import Board
from accounts.models import Profile
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy, reverse
from board.form import CreateBoardForm
from django.http import Http404
from datetime import datetime
# Create your views here.
class BoardListView(generic.ListView):
    model = Board
    paginate_by = 20
    template_name = 'board/BoardList.html'

class BoardDetailView(generic.DetailView):
    model = Board
    template_name = 'board/BoardDetail.html'

@login_required
def BoardWriteView(request):
    if request.method == 'POST':
        form = CreateBoardForm(request.POST)
        if form.is_valid():
            reqUser = request.user
            reqProfile = Profile.objects.get(user=reqUser)

            item = form.save(commit=False)
            item.writer = reqProfile.nick
            item.save()

            return redirect(reverse_lazy('board:boardList'))

    else:
        form = CreateBoardForm()

    return render(request, 'board/BoardWrite.html', {'form' : form})

@login_required
def BoardEditView(request, pk):
    editBrd = get_object_or_404(Board, pk = pk)
    reqUser = request.user
    nick = Profile.objects.get(user=reqUser).nick

    if nick != editBrd.writer:
        raise Http404("permissions denied, It is not your writing. 당신의 글이 아닙니다.")

    if request.method == 'POST':
        form = CreateBoardForm(request.POST, instance=editBrd)


        if form.is_valid():
            editBrd = form.save(commit=False)
            editBrd.createTime = datetime.now()
            editBrd.save()
            return redirect(reverse_lazy('board:boardList'))

    else:
        title = editBrd.title
        content = editBrd.contents
        form = CreateBoardForm(initial={'title': title, 'contents':content})

    return render(request, 'board/BoardWrite.html', {'form' : form})

def BoardDeleteView(request, pk):
    reqUser = request.user
    nick = Profile.objects.get(user=reqUser).nick
    try:
        item = Board.objects.get(pk=pk)
        if item.writer == nick:
            item.delete()
        else:
            raise Http404("당신의 게시글이 아닙니다. Not your Post.")

    except Board.DoesNotExist:
        raise Http404("???")

    return redirect('board:boardList')

djangoBoard/board/templates/board/BoardDetail.html
{% extends 'base.html' %}
{% block title %}Board{% endblock %}

{% block content %}
<h1>{{board}}</h1>
<h3>글쓴이 : {{ board.writer }}</h3>
<h3>작성일 : {{ board.createTime }}</h3>
<br>
{{board.contents}}
<br><br><br>
<button type="button"><a href="{% url 'board:boardList' %}">목록으로</a></button>
<button type="button"><a href="{% url 'board:boardEdit' board.id %}">수정하기</a></button>
<button type="button"><a href="{% url 'board:boardDelete' board.id %}">삭제하기</a></button>
{% endblock %}

djangoBoard/board/templates/board/BoardList.html
{% extends 'base.html' %}
{% block title %}Board{% endblock %}

{% block content %}
<h2>게시판</h2>
<button type="button"><a href="{% url 'board:boardWrite' %}">글쓰기</a></button>
<button type="button"><a href="{% url 'home' %}">메인으로</a></button>
<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Writer</th>
      <th>Date</th>
    </tr>
  </thead>
  <tbody>
    {% for board in object_list %}
      <tr>
        <td><a href="{% url 'board:boardDetail' board.id %}">{{ board }}</a></td>
        <td>{{ board.writer }}</td>
        <td>{{ board.createTime }}</td>
      </tr>
    {% endfor %}
  </tbody>
</table>


{% endblock %}

djangoBoard/board/templates/board/BoardWrite.html
{% extends 'base.html' %}
{% block title %}Board{% endblock %}

{% block content %}
<h2>글쓰기</h2>
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit" name="writeBtn">작성</button>
</form>

{% endblock %}

djangoBoard/templates/base.html
<html>
<head>
  <meta charset="utf-8">
  <title>{% block title %}Django{% endblock %}</title>
</head>
<body>
  <main>
    {% block content %}
    {% endblock %}
  </main>
</body>
</html>

djangoBoard/templates/home.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
{% if user.is_authenticated %}
  Hi {{ user.username }}!<br>
  <button type="button" name="logoutBtn"><p><a href="{% url 'logout' %}">logout</a></p></button><br>
  <button type="button" name="mypageBtn"><p><a href="{% url 'accounts:mypage' %}">My Page</a></p></button>
  <button type="button" name="boardBtn"><p><a href="{% url 'board:boardList' %}">board</a></p></button>
{% else %}
<p>You are not USER! :u </p>
<button type="button" name="loginBtn"><a href="{% url 'login' %}">login</a></button>
<button type="button" name="signupBtn"><a href="{% url 'accounts:signup' %}">signup</a></button>
{% endif %}
{% endblock %}

djangoBoard/templates/mypage.html
{% extends 'base.html' %}
{% block title %}My page{% endblock %}

{% block content %}
  <h2>My Page</h2>

    <p>ID : {{ id }}</p>
    <p>NickName : {% if nick %}{{ nick }}{% else %}No NickName{% endif %}</p>
    <p>Birth Date : {% if birth_date %}{{ birth_date }}{% else %}No birth date{% endif %}</p>
    <p>About : {% if aboutMe %}{{ aboutMe }}{% else %}No aboutMe{% endif %}</p>

<button type="button"><a href="{% url 'home' %}">메인으로</a></button>
{% endblock %}

djangoBoard/templates/signup.html
{% extends 'base.html' %}
{% block title %}Sign Up{% endblock %}

{% block content %}
  <h2>Sign Up</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Sign Up</button>
  </form>
{% endblock %}